version: '3.9'

services:
  ScheduleManagerPostgreSQL:
    container_name: ScheduleManagerPostgreSQL
    image: postgres:13.8
    environment:
      POSTGRES_DB: "ScheduleManager"
      POSTGRES_USER: "schedule_manager_app"
      POSTGRES_PASSWORD: "Qwerty$4"
    volumes:
      - .:/init.sql
      - .:/docker-entrypoint-initdb.d
    command:
      - -p 5433
    expose:
      - "5433"
    ports:
      - "5433:5433"
    network_mode: bridge
  ScheduleManagerPostgreSQLTest:
    container_name: ScheduleManagerPostgreSQLTest
    image: postgres:13.8
    environment:
      POSTGRES_DB: "ScheduleManagerTest"
      POSTGRES_USER: "schedule_manager_test"
      POSTGRES_PASSWORD: "Qwerty$4"
    volumes:
      - .:/init-test.sql
      - .:/docker-entrypoint-initdb.d
    command:
      - -p 5435
    expose:
      - "5435"
    ports:
      - "5435:5435"
    network_mode: bridge